version: '3.8'
# Podman Compose compatible configuration

services:
  # Songify Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: songify-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost
      - CORS_ORIGINS=http://localhost,http://127.0.0.1
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - songify-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount logs directory (optional)
      - backend-logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Songify Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: songify-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - songify-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Redis for session storage (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: songify-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-songify_redis_pass}
    ports:
      - "6379:6379"
    networks:
      - songify-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  songify-network:
    driver: bridge
    name: songify-network

volumes:
  backend-logs:
    name: songify-backend-logs
  redis-data:
    name: songify-redis-data
