# Production Podman Compose with SSL and advanced features
version: '3.8'
# Podman Compose compatible configuration

services:
  # Docker Socket Proxy for Security - HARDENED
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: songify-dockerproxy
    restart: unless-stopped
    environment:
      # MINIMAL Security: Only essential Docker API endpoints
      CONTAINERS: 1        # Required for container discovery
      SERVICES: 0          # Disabled - not needed
      SWARM: 0             # Disabled
      NODES: 0             # Disabled  
      NETWORKS: 0          # Disabled - reduces attack surface
      TASKS: 0             # Disabled
      # ALL dangerous endpoints explicitly disabled
      POST: 0              # No container creation
      BUILD: 0             # No image building
      COMMIT: 0            # No container commits
      CONFIGS: 0           # No config access
      DISTRIBUTION: 0      # No distribution access
      EXEC: 0              # No command execution
      IMAGES: 0            # No image management
      INFO: 0              # No system info
      PLUGINS: 0           # No plugin access
      SECRETS: 0           # No secrets access
      SESSION: 0           # No session management
      SYSTEM: 0            # No system commands
      VERSION: 0           # No version info
      VOLUMES: 0           # No volume management
      # Additional restrictions
      ALLOW_RESTARTS: 0    # No container restarts
      ALLOW_START: 0       # No container starting
      ALLOW_STOP: 0        # No container stopping
    volumes:
      # This is the ONLY place docker.sock is mounted - SECURED
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerproxy-network
    # Enhanced container security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,nodev,size=32m
    deploy:
      resources:
        limits:
          memory: 64M        # More restrictive
          cpus: '0.05'       # More restrictive
        reservations:
          memory: 32M
          cpus: '0.01'

  # Reverse Proxy with SSL termination (Secured)
  traefik:
    image: traefik:3.5.1
    container_name: songify-traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Connect to Docker via proxy instead of direct socket
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      # Security headers
      - "--api.middleware=auth"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      # NO MORE DOCKER SOCKET! Only certificates
      - traefik-letsencrypt:/letsencrypt
    networks:
      - songify-network
      - dockerproxy-network
    depends_on:
      - dockerproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # Add basic auth for dashboard security
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH:-admin:$$2y$$10$$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi}"

  # Songify Backend with production optimizations
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: songify-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=https://${DOMAIN}
      - CORS_ORIGINS=https://${DOMAIN}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./backend/.env.production
    networks:
      - songify-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - backend-logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Songify Frontend with production optimizations
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: songify-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=https://api.${DOMAIN}
    env_file:
      - ./frontend/.env.production
    networks:
      - songify-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Redis with persistence and monitoring
  redis:
    image: redis:7-alpine
    container_name: songify-redis
    restart: unless-stopped
    command: |
      redis-server 
      --appendonly yes 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    networks:
      - songify-network
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: songify-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - songify-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`metrics.${DOMAIN}`)"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"

networks:
  songify-network:
    driver: bridge
    name: songify-network
  dockerproxy-network:
    driver: bridge
    name: songify-dockerproxy-network
    internal: true  # Prevent external access to docker proxy

volumes:
  backend-logs:
    name: songify-backend-logs
  redis-data:
    name: songify-redis-data
  traefik-letsencrypt:
    name: songify-traefik-letsencrypt
  prometheus-data:
    name: songify-prometheus-data
