# Production Podman Compose with SSL and advanced features
version: '3.8'
# Podman Compose compatible configuration

services:
  # Docker Socket Proxy service removed for enhanced security
  # - Eliminates Docker socket mount vulnerability
  # - Prevents potential container escape attacks
  # - Traefik now uses file-based configuration instead

  # Reverse Proxy with SSL termination (Secured)
  traefik:
    image: traefik:latest
    container_name: songify-traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      # SECURITY: Docker provider disabled - using file provider for enhanced security
      # - No Docker socket access required
      # - Manual service configuration via static files
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.websecure.address=:8443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      # Security headers
      - "--api.middleware=auth"
    ports:
      # SECURITY: Using non-privileged ports to eliminate need for NET_BIND_SERVICE capability
      # - Port forwarding should be handled at infrastructure/load balancer level
      # - Alternative: Configure external load balancer to forward 80/443 to 8080/8443
      # SECURITY: Explicitly bind to all interfaces for public web traffic
      - "0.0.0.0:8080:8080"          # HTTP - non-privileged port (secure)
      - "0.0.0.0:8443:8443"          # HTTPS - non-privileged port (secure)
      - "127.0.0.1:8081:8081"        # Traefik dashboard - localhost only
    volumes:
      # NO MORE DOCKER SOCKET! Only certificates and configuration
      - traefik-letsencrypt:/letsencrypt
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - songify-network
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # SECURITY: No capabilities needed - using non-privileged ports eliminates NET_BIND_SERVICE requirement
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # Add basic auth for dashboard security
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH:-admin:$$2y$$10$$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi}"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Songify Backend with production optimizations
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: songify-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=https://${DOMAIN}
      - CORS_ORIGINS=https://${DOMAIN}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./backend/.env.production
    networks:
      - songify-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - backend-logs:/app/logs
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # SECURITY: No capabilities needed - container runs as fixed non-root user
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Songify Frontend with production optimizations
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: songify-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=https://api.${DOMAIN}
    env_file:
      - ./frontend/.env.production
    networks:
      - songify-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # SECURITY: No capabilities needed - ownership changes happen at build time
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # Redirect HTTP to HTTPS on non-privileged ports
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.port=8443"
      - "traefik.http.routers.frontend-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Redis with persistence and monitoring
  redis:
    image: redis:8.0.3-alpine3.21
    container_name: songify-redis
    restart: unless-stopped
    command: |
      redis-server 
      --appendonly yes 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    networks:
      - songify-network
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: songify-prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"  # Prometheus - localhost only for security
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - songify-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`metrics.${DOMAIN}`)"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  songify-network:
    driver: bridge
    name: songify-network
# dockerproxy-network removed - no longer needed after security remediation

volumes:
  backend-logs:
    name: songify-backend-logs
  redis-data:
    name: songify-redis-data
  traefik-letsencrypt:
    name: songify-traefik-letsencrypt
  prometheus-data:
    name: songify-prometheus-data
