# Traefik Dynamic Configuration - No Docker Socket Required
# This file defines routes statically instead of auto-discovery

http:
  routers:
    # Frontend routing
    frontend:
      rule: "Host(`${DOMAIN}`)"
      service: frontend-service
      tls:
        certResolver: letsencrypt
    
    # Backend API routing  
    backend:
      rule: "Host(`api.${DOMAIN}`)"
      service: backend-service
      tls:
        certResolver: letsencrypt
    
    # Traefik dashboard
    traefik-dashboard:
      rule: "Host(`traefik.${DOMAIN}`)"
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth

  services:
    # Frontend service
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://songify-frontend:80"
        healthCheck:
          path: "/health"
          interval: "30s"
    
    # Backend service
    backend-service:
      loadBalancer:
        servers:
          - url: "http://songify-backend:3000"
        healthCheck:
          path: "/health"
          interval: "30s"

  middlewares:
    # Basic authentication for dashboard
    auth:
      basicAuth:
        users:
          - "admin:$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"
    
    # Security headers
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"
